version: "2"
services:
  web:
    image: smolka/capitalonedemo
    ports:
      - 8080:8080
    environment:
      - DB_NAME=capitalone
      - DB_USER=vista
      - DB_PASS=vista
      - SCHEMA=capitalone
      - POSTGREDB_URL=jdbc:postgresql://192.168.99.100:5432
    depends_on: 
      - db 
  db:
    build: ./postgres
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=capitalone
      - DB_USER=vista
      - DB_PASS=vista
      - SCHEMA=capitalone
  
